#include "framework.h"


#include "user.cpp"


#include "user_command.cpp"
#include "user_controller.cpp"
#include "user_control_event.cpp"
#include "user_copydesk.cpp"
#include "user_create.cpp"
#include "user_elemental.cpp"
#include "user_frame.cpp"
//#include "user_frame_window.cpp"
#include "user_interaction.cpp"
#include "user_interaction_base.cpp"
#include "user_interaction_child.cpp"
#include "user_interaction_impl.cpp"
#include "user_interaction_impl_base.cpp"
#include "user_interactive.cpp"
#include "user_job.cpp"
#include "user_key.cpp"
#include "user_menu.cpp"
#include "user_menu_command.cpp"
#include "user_menu_item.cpp"
#include "user_mouse.cpp"
#include "user_place_holder.cpp"
#include "user_place_holder_container.cpp"
#include "user_primitive.cpp"
#include "user_print_job.cpp"
#include "user_style.cpp"
#include "user_style_base.cpp"
#include "user_style_composite.cpp"
#include "user_theme.cpp"
#include "user_tooltip.cpp"
#include "user_validate.cpp"
#include "user_windowing.cpp"
#include "user_window_map.cpp"
#include "user_window_util.cpp"


#include "user_message_queue.cpp"

