#include "framework.h"


#include "user.cpp"
#include "user_box.cpp"
#include "user_button.cpp"
#include "user_control.cpp"
#include "user_control_bar.cpp"
#include "user_control_descriptor.cpp"
#include "user_control_descriptor_set.cpp"
#include "user_document.cpp"
#include "user_form_callback.cpp"
#include "user_form_update_hint.cpp"
#include "user_form_window.cpp"
#include "user_frame_window.cpp"
#include "user_impact.cpp"
#include "user_impact_system.cpp"
#include "user_impact_update_hint.cpp"
#include "user_message.cpp"
#include "user_message_queue.cpp"
#include "user_plain_edit.cpp"
#include "user_plain_text_data.cpp"
#include "user_scroll.cpp"
#include "user_scroll_bar.cpp"
#include "user_server.cpp"
#include "user_user.cpp"
#include "user_view_container.cpp"
#include "user_view_creator.cpp"
#include "user_wait_cursor.cpp"



