#include "framework.h"


#include "str_base64.cpp"
#include "str_c.cpp"
#include "str_core.cpp"
#include "str_dup.cpp"
#include "str_format.cpp"
#include "str_from_integer.cpp"
#include "str_hex.cpp"
#include "str_international.cpp"
#include "str_international_locale_schema.cpp"
#include "str_istring.cpp"
#include "str_manager.cpp"
#include "str_parse.cpp"
#include "str_simple.cpp"
#include "str_str.cpp"
#include "str_string.cpp"
#include "str_stringtow.cpp"
#include "str_strw.cpp"
#include "str_strx.cpp"
#include "str_sz.cpp"
#include "str_tokenizer.cpp"
#include "str_to_integer.cpp"
#include "str_verisimple_wstring.cpp"
#include "str_wtostring.cpp"
#include "str_x.cpp"


