#include "framework.h"


#include "file.cpp"
#include "file_binary_buffer.cpp"
#include "file_buffered_buffer.cpp"
#include "file_c.cpp"
#include "file_circular_buffer.cpp"
#include "file_composite.cpp"
#include "file_cpp.cpp"
#include "file_dir.cpp"
#include "file_dir2.cpp"
#include "file_edit_file.cpp"
#include "file_exception.cpp"
#include "file_file.cpp"
#include "file_file_base.cpp"
#include "file_file_stream.cpp"
#include "file_folder_watch.cpp"
#include "file_html_file.cpp"
#include "file_md5.cpp"
#include "file_memory_file.cpp"
#include "file_path.cpp"
#include "file_plain_text_stream.cpp"
#include "file_reader.cpp"
#include "file_seekable.cpp"
#include "file_serializable.cpp"
#include "file_serialize.cpp"
#include "file_set.cpp"
#include "file_simple_binary_file.cpp"
#include "file_stdio_file.cpp"
#include "file_stream.cpp"
#include "file_stream2.cpp"
#include "file_string_file.cpp"
#include "file_text_file.cpp"
#include "file_writer.cpp"
#include "file_writer_flush.cpp"



